apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: arbitrary

# Example configuration for the webserver
# at https://github.com/monopole/hello
labels:
  - includeSelectors: true
    pairs:
      org: lil

resources:
- app.yaml
